apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-http-server
  labels:
    app: python-http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-http-server
  template:
    metadata:
      labels:
        app: python-http-server
    spec:
      containers:
      - name: python-http-server
        image: bobcrutchley/python-http-server
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: python-http-server
  labels:
    run: python-http-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    run: python-http-server

