---
- name: python-http-server-ci
  box: centos/7
  cpus: 1
  memory: 4096
  private_ip: 10.0.10.10
  package_manager: yum
  packages:
  - wget
  - unzip
  - git
  - docker
  scripts:
  - vim_config 
  - docker
  - copy_project
...

